### PR TITLE
Bump to 1.8.14

### PR DESCRIPTION
**Pull request by bluescarni**

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@isuruf I had to add a build time dependency on texlive-core for Linux and OSX. One of the tests in the test suite was failing because it was testing the ``\cite`` doxygen command, which requires the presence of bibtex to function correctly.

**Comment by isuruf** [comment]
@bluescarni, would you like to become a maintainer in this feedstock?

**Comment by bluescarni** [comment]
I can be a comaintainer.

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
