### PR TITLE
Doxygen 1.9.4

### PR DESCRIPTION
**Pull request by VincentRouvreau**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tadeu** [comment]
From the build, it looks like it's still targeting SDK 10.9.

**Comment by VincentRouvreau** [comment]
> From the build, it looks like it's still targeting SDK 10.9.

Nice catch ! Do you think it also requires `MACOSX_DEPLOYMENT_TARGET` ? Or `MACOSX_SDK_VERSION` should be enough ? I can try to rollback [4b33ad7](https://github.com/conda-forge/doxygen-feedstock/pull/31/commits/4b33ad7f284036de7cb4e3841da2838b1a9b56af) if it works.

**Comment by tadeu** [comment]
TBH I'm not familiar with building packages for macOS, but yeah, let's give it a try to `MACOSX_DEPLOYMENT_TARGET`.

**Comment by MuellerSeb** [comment]
Any news on this?

**Comment by VincentRouvreau** [comment]
> Any news on this?

@MuellerSeb Unfortunately, no... I think I am going to close this PR and try again later.
If you want, you can try to do it, no worries ;-)

**Pull request closed without merging**
