### PR TITLE
Provide 1.8.14 for ppc/arm

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
I had to get `1.8.14` from different sources because the original URLs are no longer available, but seems to work! Ready for review!

**Comment by isuruf** [comment]
https://github.com/conda-forge/doxygen-feedstock/tree/1.8.14

**Comment by jaimergp** [comment]
Thanks!

**Pull request closed without merging**
