### PR TITLE
update sha256 for 1.9.3

### LINKED ISSUE #26: Doxygen 1.9.3 not avialable due to SHA mismatch in CI
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
The CI for this feedstock failed after merging #25 due to a SHA mismatch:
```bash
RuntimeError: SHA256 mismatch: 'eeee71516ddb0d8c057480c2fcd094e63b639146d09ba70b6fd013ca48a25b6a' != 'adcd968e10f27a15c956aaad86f544174f0e3d2d26d8d978929513ceeb09c19d'
```

### PR DESCRIPTION
**Pull request by MuellerSeb**
Closes #26 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MuellerSeb** [comment]
@conda-forge-admin, please rerender

**Comment by MuellerSeb** [comment]
For some reason if I run `sha256sum` locally, I get another one:
```bash
$ sha256sum doxygen-1.9.3.src.tar.gz
f352dbc3221af7012b7b00935f2dfdc9fb67a97d43287d2f6c81c50449d254e0
```

**Comment by MuellerSeb** [comment]
@tadeu ping :-)

**Comment by tadeu** [comment]
This is odd, I'm getting the same SHA256 as you, `f352dbc3221af7012b7b00935f2dfdc9fb67a97d43287d2f6c81c50449d254e0`, which is different than the last two in the recipe.

**Comment by tadeu** [comment]
Perhaps they updated the file again? They also have releases on GitHub, perhaps we could change to use those, to be more stable?

For example: https://github.com/doxygen/doxygen/releases/tag/Release_1_9_3

**Review by MuellerSeb — COMMENTED** [review]
I already tried this sha256 but had to change it. Does conda-forge maybe cache files in CI?!

**Comment by tadeu** [comment]
> I already tried this sha256 but had to change it.

Ahh, OK, sorry for the noise then, feel free to remove my commit 😅!

> Does conda-forge maybe cache files in CI?!

Hmm, that would be weird, but yeah, it's an explanation (maybe Azure is caching it). It would be very weird for a server to serve different files depending on the request. Since there are 3 different hashes so far, I'm not sure about merging it without further research on what's going on, forwarding this to @isuruf and @bluescarni.

**Comment by tadeu** [comment]
@conda-forge-admin, please restart ci

**Comment by MuellerSeb** [comment]
@bluescarni @isuruf @tadeu do you have any clue what is going wrong?

**Comment by VincentRouvreau** [comment]
@tadeu @MuellerSeb Even if the conda package failed for Windows, I think we can close this issue thanks to https://github.com/conda-forge/doxygen-feedstock/pull/30

**Pull request closed without merging**
