### PR TITLE
Doxygen version 1 9 4

### PR DESCRIPTION
**Pull request by VincentRouvreau**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

A new PR for doxygen 1.9.4 conda package

### CODE REVIEW

**Comment by VincentRouvreau** [comment]
Asked for help on https://github.com/doxygen/doxygen/issues/9557

**Review by tadeu — APPROVED** [review]
🎉🚀

**Comment by tadeu** [comment]
Thanks @VincentRouvreau, and thanks for the fix @isuruf!

**Comment by VincentRouvreau** [comment]
@tadeu @isuruf Is #10 fixed ? It seems the power pc version is available, no ?

**Pull request merged**
