### PR TITLE
v1.9.6

### PR DESCRIPTION
**Pull request by tdegeus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by tdegeus** [comment]
@conda-forge/doxygen Ready for review. The powerpc build will last at least two hours from here based on what I have seen on other PRs. We can also merge when it is done, but if you have any remarks now would be good ;)

**Comment by bluescarni** [comment]
@tdegeus LGTM!

**Comment by tdegeus** [comment]
Thanks @bluescarni . Good to go ! ( ping @conda-forge/doxygen )

**Comment by tdegeus** [comment]
@bluescarni I don't want to be pedantic, but I want to finish something, and it would help me to have this merged. Ref : https://github.com/doxygen/doxygen/issues/9940

**Pull request merged**
